development:
  database: rails_angular_bootstrap_seed_dev
  adapter: postgresql
  host: localhost
  username:
  password:
  encoding: unicode
  pool: 5
  timeout: 5000

test: &test
  database: rails_angular_bootstrap_seed_test
  adapter: postgresql
  host: localhost
  username:
  password:
  encoding: unicode
  pool: 5
  timeout: 5000

staging:
  database: rails_angular_bootstrap_seed_staging
  adapter: postgresql
  host: localhost
  username:
  password:
  encoding: unicode
  pool: 5
  timeout: 5000

production:
  database: rails_angular_bootstrap_seed_production
  adapter: postgresql
  host: localhost
  username:
  password:
  encoding: unicode
  pool: 5
  timeout: 5000

cucumber:
  <<: *test